### ISSUE TITLE
Change gemspec homepage url 

### ISSUE THREAD

**Issue by drnic** [demandforce/rack-oauth2-server#1]
Change the homepage url to https://github.com/flowtown/rack-oauth2-server (this is the link that's on the RubyGems.org page). Sorry I don't have time to pull down the source + fix it. Damn, I could have done it instead of writing that. Damn.

**Comment by fairchild** [comment]
Fixed the gemspec. 
Check the pull request.

**Comment by assaf** [comment]
Fixing, thanks.
