### ISSUE TITLE
redirect_url check to rigid

### ISSUE THREAD

**Issue by mwawrusch** [demandforce/rack-oauth2-server#11]
I am developing a chrome extension for a new site of mine that uses rack-oauth2-server as the backend. It needs to call the oauth2 endpoint with 

http://tagli.st/oauth/authorize?response_type=token&client_id=CLIENTID&redirect_uri=chrome-extension://jiabnokcakaemncikpofbekjkaolhenl/background.html

right now this returns a 

Redirect URL must point to HTTP/S location

The latest specs state that the redirect_url must be an absolute url, but they do not specify that it has to be http/https. Would be great if you could allow for this use case as well.

BTW, thanks again for the great gem.

**Comment by assaf** [comment]
Can you make the change and send a pull request?

**Comment by mwawrusch** [comment]
k, coming monday.

**Comment by assaf** [comment]
Pull request merged, so this should be closed now
