### ISSUE TITLE
Support for Out of Band authorization

### ISSUE THREAD

**Issue by ismasan** [demandforce/rack-oauth2-server#13]
Not sure this is a valid token as I'm a bit unclear this is still part of the spec (couldn't find it in the draft but some providers do offer OOB auth).

Do you have plans to support oob authorization? Specifically for desktop and command-line clients

**Comment by assaf** [comment]
"Out of band" means not part of the protocol, hence it's not covered by the spec.

The API is documented in the README file, look for "Methods You’ll Want To Use From Your App".

**Comment by ismasan** [comment]
Ok, sorry. I see now that I was confusing OAuth2 with the request token dance in OAuth1. Basically allowing for redirect_uri => 'oob' for pin-based authorization in desktop apps. Thanks.

**Comment by assaf** [comment]
What part of the spec are you referring to?

**Comment by ismasan** [comment]
Request token http://oauth.net/core/1.0a/#rfc.section.6.1.1 (see "oauth_callback"). Again that's OAuth1 so nevermind. It also confused me that Google does cater for the "oob" case http://code.google.com/apis/accounts/docs/OAuth2.html#IA

I'm still not sure what the recommended flow is for granting access to desktop / command line apps, other that log into their accounts and create a token for themselves

**Comment by assaf** [comment]
The easiest is grant type password: client sends username/password, gets back an access token.

If you want to do something like Google's, designate an end point on the server that shows the access token and instructions to the end-user. Then have clients register with that endpoint as the redirect_uri. There's no reason for it to be some weird URI.

**Comment by ismasan** [comment]
Re. passwords: yes that's the first I tried and it works like a charm (thanks!). But it also slightly defeats the point IMO, because users need to expose their passwords to 3rd party clients. 

So you're saying that the redirect_uri is an endpoint in the auth provider app, instead of the client's. That should work, but isn't it odd that it's the client responsability to provide that? What the client is basically asking is "generate a code and show it to me on your site. Don't redirect back to anywhere". It seems to me that this could be a directive in the request just like grant_type is. In google's (and OAuth1) solution you specifically tell the server to go into "oob" mode.

**Comment by assaf** [comment]
What the client is basically asking is "redirect to a page with instructions on how to copy & paste a token". Pick an end point where that page exists and have the client use that as the redirect_uri.

That's what Google is asking you do to, except they replaced an HTTP URL with some magic value.

**Comment by ismasan** [comment]
Yes, but passing "oob" leaves it up to the provider to pick that endpoint (for example the provider can choose do the auth flow as a single page JS app). If the clients passes that URL the provider can't ever change it. Also the endpoint needs to be store along with the client application record.

But it's alright. I can do that in my fork. Thanks.
