### ISSUE TITLE
Raises error in v. 2.3, 2.4

### ISSUE THREAD

**Issue by tarasstruk** [demandforce/rack-oauth2-server#20]
`oauth2-server --db oauth2 list
/Users/taras/.rvm/gems/ruby-1.9.2-p290/gems/rack-oauth2-server-2.3.0/bin/oauth2-server:14:in `<top (required)>': undefined method `database=' for Rack::OAuth2::Server:Class (NoMethodError)
    from /Users/taras/.rvm/gems/ruby-1.9.2-p290/bin/oauth2-server:19:in `load'`

**Comment by msaffitz** [comment]
There's a patch for this in #23
