### ISSUE TITLE
Sample provider and client?

### ISSUE THREAD

**Issue by 1xch** [demandforce/rack-oauth2-server#22]
After playing with other options I've been using this: https://github.com/freerange/oauth2-provider, and then I stumbled across this. I'm curious how this compares.

  This is a little daunting for me, but I'll play with it  bit to see what I can do, but I'm curious is if anyone has a sample of this in a rails application as a provider. Where is this being used?

  I would be interested if it integrates with devise or just in general what can be done with managing users in a cross-application environment.

**Comment by assaf** [comment]
Integration with Devise would be nice.
