### ISSUE TITLE
AccessGrant not finding records in database

### ISSUE THREAD

**Issue by joshavant** [demandforce/rack-oauth2-server#24]
In  lib / rack / oauth2 / models / access_grant.rb, line 11, I am not getting anything back from the database, when searching for a client ID code, despite previously using rack-oauth2-server to successfully create a client entry (and verifying this entry in the database).

Testing this, I used this code with a non-revoked client ID from the database:
query = collection.find_one({ :_id=> "4e36e95cd5eefd0bad000001", :revoked=>nil })
puts "query.inspect: " + query.inspect

...and I get:
'query.inspect: nil'

The output expected was a successfully located client record.

**Comment by assaf** [comment]
AccessGrant is keyed by authorization code. You can get all the authorization codes for a client, but you'll need to query by client_id, not _id.

**Comment by joshavant** [comment]
Ah! Should there be a `client_id` field in my record for this client?

Right now, my client test record is constructed, like so:
http://i.imgur.com/ulces.png

**Comment by assaf** [comment]
If you're looking in the **AccessGrant** collection, you're going to find nothing but access grants. Access grants reference clients, but access grants are **not** clients.

**Comment by joshavant** [comment]
Of course, but the image posted above was from my `oauth2.clients` collection.

**Comment by assaf** [comment]
And the problem is?

**Comment by joshavant** [comment]
In rails console, this code fails to return a result:

> > query = Rack::OAuth2::Server::AccessGrant.collection.find_one({ :_id=> "4e36e95cd5eefd0bad000001", :revoked=>nil })
> > => nil
> > query.inspect
> > => "nil"

With this client entry in the `oauth2.clients` collection:
http://i.imgur.com/ulces.png

**Comment by assaf** [comment]
Have you tried looking for clients in the collection called **Clients**?

**Comment by joshavant** [comment]
Which `Clients` collection?

All that's in my database is the `oauth2.clients` collection which was auto-generated by the gem (lib / rack / oauth2 / models / client.rb, line 69):
`def collection
  Server.database["oauth2.clients"]
end`

**Comment by assaf** [comment]
Here's the clue and my last response to this thread: if a class names a collection through the **collection** method, then that class will only ever retrieve records from that one collection.
